language: cpp
python: 
  - "3.7"
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.8

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python3-setuptools python-dev
  - sudo pip3 install -U pip virtualenvwrapper
  - python3 -V
  - pip3 -V
  - virtualenv -p python3 venv
  - source venv/bin/activate
install:
  - pip3 install cmake
  - python3 setup.py sdist
  - pip3 install --verbose dist/*.tar.gz
script:
  - python3 setup.py test
